config/routes.rb
Rails.application.routes.draw do

  post '/books/submit', to: 'books#submit'
  get '/books/issuedbook', to: 'books#issuedbook'
  get '/books/release', to: 'books#release'
  get '/people/new', to: 'people#new'
  devise_for :people
  scope "/librarian" do
    resources :people
  end
  resources :books
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :person do
      root :to => 'books#index', as: :authenticated_root
  end
  root to: "books#index"
end

app/models/person.rb
class Person < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    validates_confirmation_of :password
    has_many :book

    validates_presence_of :first_name, :email
    before_save :assign_role

#Check this definition it may cause issues
    def assign_role
      self.role_id = 3 if self.role_id.nil?
    end

#define roles here
    def librarian?
      self.role_id == 1
    end
    def prime_user?
      self.role.id == 2
    end
    def user?
      self.role.id == 3
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_person!
  #before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @joined_on = @person.created_at.to_formatted_s(:short)
    if @person.current_sign_in_at
      @last_login = @person.current_sign_in_at.to_formatted_s(:short)
    else
      @last_login = "Never"
    end
  end

  # GET /people/new
  def new
    #@person = Person.new
  end

  # GET /people/1/edit
  def edit
    authorize! :edit, @book
  end

  # POST /people
  # POST /people.json
  def create
    #@person = Person.new(person_params)
    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    if person_params[:password].blank?
      person_params.delete(:password)
      person_params.delete(:password_confirmation)
    end

    successfully_updated = if needs_password?(@person, person_params)
                             @person.update(person_params)
                           else
                             @person.update_without_password(person_params)
                           end

    respond_to do |format|
      if successfully_updated
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_person
    #  @person = Person.find(params[:id])
    #end
    protected
    def needs_password?(person, params)
      params[:password].present?
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :gender, :dob, :phone_number, :email, :password, :password_confirmation, :role_id)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

    <div class="field">
      <%= f.label :gender %>
      <%= f.radio_button :gender, 'Male' %> Male <%= f.radio_button :gender, 'Female' %> Female
    </div>

  <div class="field">
    <%= f.label :dob %>
    <%= f.date_select :dob, {:start_year => Date.current.year, :end_year => 1920} %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, placeholder: "Leave blank if unchanged" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
     <%= f.label :role_id %>
    <%= f.collection_select :role_id, Role.all, :id, :role_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Dob</th>
      <th>Number</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.gender %></td>
        <td><%= person.dob %></td>
        <td><%= person.phone_number %></td>
        <td><%= person.email %></td>
        <td><%= Role.find(person.role_id).role_name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @person.gender %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @person.dob %>
</p>

<p>
  <strong>Number:</strong>
  <%= @person.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= Role.find(@person.role_id).role_name %>
</p>

<p>
  <strong>Joined on:</strong>
  <%= @joined_on %>
</p>
<p>
  <strong>Last logged in on:</strong>
  <%= @last_login %>
</p>
<p>
  <strong>No. times logged in:</strong>
  <%= @person.sign_in_count %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>