config/routes.rb
Rails.application.routes.draw do

  post '/books/submit', to: 'books#submit'
  get '/books/issuedbook', to: 'books#issuedbook'
  get '/books/release', to: 'books#release'
  get '/people/new', to: 'people#new'
  devise_for :people
  scope "/librarian" do
    resources :people
  end
  resources :books
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :person do
      root :to => 'books#index', as: :authenticated_root
  end
  root to: "books#index"
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_person!
  #before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
	if params[:search]
        @books = Book.where("book_name like ? and person_id is null", "#{params[:search]}%")
	else
      @books = Book.where("person_id is null and allowed_role_id >= ?", current_person.id)
		#@books = Book.where("allowed_role_id == ? ", "123")# In place of 123 we need to add the value of role_id to get the role based books
	end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    #@book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # GET /books/1
  # GET /books/1.json
  def submit
    currentUser = current_person.id
    temp = params[:book_name]
      temp.each do |bookid|
          logger.info "***************#{bookid}"
          fetchedBook = Book.find(bookid) 
          fetchedBook.person_id = currentUser
          fetchedBook.save
      end
     redirect_to :action=>"index" 
    logger.info "Unnati borrows book #{params[:book_name]}"
  end

  # GET /books/1
  # GET /books/1.json
  def release
      logger.info "************** #{params[:book_id]}"
    @book = Book.find(params[:book_id])
@book.person_id = '';
@book.save
redirect_to :action=>"issuedbook"
  end

def issuedbook
	currentUser = current_person.id
	if Person.find(currentUser).librarian?
		@books = Book.where("person_id is not null")
	else
		@books = Book.where("person_id = ?", currentUser)
	end
end

  # POST /books
  # POST /books.json
  def create
    #@book.person_id = current_person.id
    #@book = Book.new(book_params)
    @book.widrawal_status = "false"

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_book
    #  @book = Book.find(params[:id])
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book_name, :book_author, :widrawal_status, :allowed_role_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_name %>
    <%= f.text_field :book_name %>
  </div>

  <div class="field">
    <%= f.label :book_author %>
    <%= f.text_field :book_author %>
  </div>


    <div class="field">
     <%= f.label :allowed_role_id %>
    <%= f.collection_select :allowed_role_id, Role.all, :id, :role_name %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_list.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_name %>
    <%= f.text_field :book_name %>
  </div>

  <div class="field">
    <%= f.label :book_author %>
    <%= f.text_field :book_author %>
  </div>

  <div class="field">
    <%= f.label :widrawal_status %>
    <%= f.check_box :widrawal_status %>
  </div>

  <div class="field">
    <%= f.label :allowed_role_id %>
    <%= f.text_field :allowed_role_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<%= form_tag(books_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Book" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>
</br>

<%= form_for :book,url: "/books/submit",method: "post" do %>
<table border=1 cellpadding=0 cellspacing=0>
  <thead>
    <tr>
	<% if !Person.find(current_person.id).librarian? %>
      <th>Select</th>
	  <% end %>
      <th>Book name</th>
      <th>Book author</th>
      <th>Allowed role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
	  <% if !Person.find(current_person.id).librarian? %>
        <td><%= check_box_tag 'book_name[]', book.id %></td>
		<% end %>
        <td><%= book.book_name %></td>
        <td><%= book.book_author %></td>
        <td><%= Role.find(book.allowed_role_id).role_name %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if !Person.find(current_person.id).librarian? %>
<%= submit_tag "Borrow Books", :name => nil %>
<% end %>
<%= link_to 'New Book', new_book_path %>
<% end %>

app/views/books/issuedbook.html.erb
<table border=1 cellpadding=0 cellspacing=0>
  <thead>
    <tr>
      <th>Book name</th>
      <th>Book author</th>
	  <th>Issued To</th>
      <th>Allowed role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.book_name %></td>
        <td><%= book.book_author %></td>
		<td><%= Person.find(book.person_id).email %></td>
        <td><%= Role.find(book.allowed_role_id).role_name %></td>
        <td><%= link_to 'Show', book %></td>
          <td><%= link_to "Release", books_release_path(:book_id => book.id), data: { confirm: 'Are you sure?' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/release.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book name:</strong>
  <%= @book.book_name %>
</p>

<p>
  <strong>Book author:</strong>
  <%= @book.book_author %>
</p>

<p>
  <strong>Widrawal status:</strong>
  <%= @book.widrawal_status %>
</p>

<p>
  <strong>Allowed role:</strong>
  <%= @book.allowed_role_id %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book name:</strong>
  <%= @book.book_name %>
</p>

<p>
  <strong>Book author:</strong>
  <%= @book.book_author %>
</p>

<p>
  <strong>Widrawal status:</strong>
  <%= @book.widrawal_status %>
</p>

<p>
  <strong>Allowed role:</strong>
  <%= @book.allowed_role_id %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/submit.html.erb
<p id="notice1"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>         </th>
      <th>Book name</th>
      <th>Book author</th>
      <th>Widrawal status</th>
      <th>Allowed role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
    if <%= book.widrawal_status %> <=> true
      <tr>
        <td><%= check_box_tag :book_name,:value =>book.book_name %></td>
        <td><%= book.book_author %></td>
        <td><%= book.widrawal_status %></td>
        <td><%= book.allowed_role_id %></td>
      </tr>
    end
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Release', books_release_path %>
<%= link_to 'All Books', books_path %>