config/routes.rb
Rails.application.routes.draw do

  post '/books/submit', to: 'books#submit'
  get '/books/issuedbook', to: 'books#issuedbook'
  get '/books/release', to: 'books#release'
  get '/people/new', to: 'people#new'
  devise_for :people
  scope "/librarian" do
    resources :people
  end
  resources :books
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :person do
      root :to => 'books#index', as: :authenticated_root
  end
  root to: "books#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if person_signed_in? %>
      Signed in as <%= current_person.email %>. Not you?
      <%= link_to "Edit profile", edit_person_registration_path %>
      <%= link_to "Sign out", destroy_person_session_path, :method => :delete %>
      <br/>
      <%= link_to "Issued Books", books_issuedbook_path %>
      <%= link_to "User list", people_path %>
      <%= link_to "Add Book", new_book_path %>
    <% else %>
      <%= link_to "Sign up", new_person_registration_path %> or <%= link_to "sign in", new_person_session_path %>
    <% end %>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </body>
</html>